version: '3.5'

# todo: clean-up, use mysql
services:
    laravel-app:
        build:
            context: '.'
#            args:
#                uid: ${UID}
        container_name: laravel-app
#        environment:
#            - APACHE_RUN_USER=#${UID}
#            - APACHE_RUN_GROUP=#${UID}
        volumes:
            - .:/var/www/html
        ports:
            - 8000:80
