version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./deploy/php/local.ini:/usr/local/etc/php/conf.d/local.ini
#        ports:
#            - '${APP_PORT:-80}:1999'
        networks:
            - app-network
#        depends_on:
#            - nginx

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8180:80"
            - "8143:443"

#            - "8080:80"
#            - "80:80"
#            - "443:443"
        volumes:
            - ./:/var/www
            - ./deploy/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
