version: '3.5'

services:
    laravel-app:
        build:
            context: '../..'
            dockerfile: ../../Dockerfile
#            args:
#                uid: ${UID}
        image: digitalocean.com/php
        restart: unless-stopped
        tty: true

        container_name: laravel-app
        environment:
            SERVICE_NAME: laravel-app
            SERVICE_TAGS: dev
#        environment:
#            - APACHE_RUN_USER=#${UID}
#            - APACHE_RUN_GROUP=#${UID}
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:80"
        networks:
            - laravel-app-network

    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'routes-db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_PASSWORD: ""
#            DB_DATABASE: laravel
#            SERVICE_TAGS: dev
#            SERVICE_NAME: mysql
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-app-network

networks:
    laravel-app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
